### ISSUE TITLE
readlink syntax

### ISSUE THREAD

**Issue by tblake84** [ff36/halo-installer-ubuntu#9]
Proper syntax to read symbolic link on Ubuntu is "readlink".  Kept getting "readLink: command not found" error and edited installer to reflect proper syntax to fix issue.

**Comment by tarkal** [comment]
Can you either send a pull request with fixes or post your changes here.

**Comment by tblake84** [comment]
New syntax is as follows.

Starting on line 688:
`    ########### Move this installer to the bin
    cp "$(readlink -f $0)" "${IST_FILE}"
    rm "$(readlink -f $0)"
`

**Comment by tarkal** [comment]
fixed in `develop` `1.0.11`
